### ISSUE TITLE
Cannot read property '__ConsumeGenerator__' of null

### ISSUE THREAD

**Issue by pavel** [caolan/highland#518] opened 2016-08-05 16:31 UTC
### Environment

```
Highland: 3.0.0-beta.2
Node: v6.3.1
OS: Linux
```

### Example (CoffeeScript)
```coffee
Stream = require "highland"

fn = ->
	Stream Promise.resolve([])
		.map (data) ->
			console.log "map", data
			Stream Promise.resolve([])
		.parallel 1
		.consume (err, data, push, next) ->
			push null, Stream.nil

Stream([
	Stream([["data"]])
	fn().collect()
])
	.parallel 2
	.tap (data) -> console.log "tap", data
	.collect()
	.each (data) -> console.log "each", data
```

### Error

```
/home/user/highland-bug/node_modules/highland/lib/index.js:1280
        if (gen.__ConsumeGenerator__) {
               ^

TypeError: Cannot read property '__ConsumeGenerator__' of null
  at Stream._runGenerator (/home/user/highland-bug/node_modules/highland/lib/index.js:1280:16)
  at Immediate.<anonymous> (/home/user/highland-bug/node_modules/highland/lib/index.js:791:26)
  at runCallback (timers.js:570:20)
  at tryOnImmediate (timers.js:550:5)
  at processImmediate [as _immediateCallback] (timers.js:529:5)
```

---
Does only happen when `Promise` are in use.
Substituting `Promise.resolve([])` to `[[]]` works without error.

**Comment by pavel** [comment] 2016-08-05 17:47
Replacing `.parallel 1` with `.series()` or `.flatten()` also resolves the problem.

**Comment by pavel** [comment] 2016-08-05 17:55
Replacing `.parallel 1` with `.series()` eliminates the error.

**Comment by vqvu** [comment] 2016-08-06 01:16
I think this is an easy fix. The call to `_runGenerator` [here](https://github.com/caolan/highland/blob/3.0.0/lib/index.js#L796) needs to check if the generator still exists. It could have been destroyed by downstream.

I'm away from my computer for the new week or so though, so I won't be able to get around to this until then.

**Comment by pavel** [comment] 2016-08-06 14:46
@vqvu Like [here](https://github.com/caolan/highland/blob/3.0.0/lib/index.js#L1112-L1114)?

**Comment by vqvu** [comment] 2016-08-06 15:51
Yeah.

**Comment by svozza** [comment] 2016-08-06 16:27
I'm having trouble reproducing this, I translated it into ES5 here to create a failing test case but it passes for me. Is there something wrong with my code here?

```js
var fn = function() {
        return _(Promise.resolve([]))
            .map(function (x) {
                return _(Promise.resolve([]));
            })
            .parallel(1)
            .consume(function (err, data, push, next) {
                push(null, _.nil);
            });
    };

    _([_([['data']]),
    fn().collect()])
        .parallel(2)
        .collect()
        .each(function(ys) {
            console.log(ys);
        });
```

**Comment by vqvu** [comment] 2016-08-06 18:28
Here's a more explicit test case.

```javascript
var _ = require("highland");

// Code path is this:
// - push(...) causes s.destroy() to be queued.
// - next2 is queued.
// - next1 is executed, which queues _runGenerator
// - destroy() runs and clears the _generator.
// - next2 runs and sets the _generator_requested flag.
// - _runGenerator runs and is allowed to be executed because _generator_requested
//   was set.
var s = _(function (push, next) {
    setTimeout(function () {
        push(new Error("error"));
        _.setImmediate(next); // next2
        next(); // next1
    }, 0);
});

s.pull(function (err, x) {
    // This pull is required to un-pause the stream.
    s.pull(function () {
        // Ignore.
    });

    _.setImmediate(function () {
        s.destroy();
    });
});
```

I thought about this more and I think the correct fix is to check for `_explicitly_destroyed` at the start of `_next_fn` and immediately return if it's `true`. I believe this also needs to be done in `_writeOutgoing`.

**Comment by svozza** [comment] 2016-08-06 20:51
Ah yes, this causes failures for me now too. I'll raise a PR in the morning.

**Comment by vqvu** [comment] 2016-08-07 17:22
@pavel, since we're not testing against the test case that you provided, can you verify that #521 fixes the issue for you?

**Comment by pavel** [comment] 2016-08-08 18:44
@vqvu I've verified, and the fix does resolve the problem.

**Comment by vqvu** [comment] 2016-08-09 03:53
#521 was merged, so I will close this.

**Closed by vqvu** 2016-08-09 03:53 UTC
Labels: 3.x, bug
