### ISSUE TITLE
To Nodejs Stream

### ISSUE THREAD

**Issue by ronag** [caolan/highland#279] opened 2015-04-19 17:40 UTC
I'm using the AWS SDK to upload a stream to a S3 bucket. However, it complains that I'm providing an unsupported body when I send it a highland stream. How can I convert a highland stream into a regular nodejs stream?

i.e.

This doesn't work:

```
 _ 
  .wrapCallback((options, cb) => s3.upload(options, cb))
  .call(null, {
    Bucket: bucket,
    Body: _(process.stdin),
    Key: key
  })
```
These work:
```
 _ 
  .wrapCallback((options, cb) => s3.upload(options, cb))
  .call(null, {
    Bucket: bucket,
    Body: process.stdin, // won't work in practice
    Key: key
  })
```

```
 _ 
  .wrapCallback((options, cb) => s3.upload(options, cb))
  .call(null, {
    Bucket: bucket,
    Body: new stream.Readable().wrap(_(process.stdin)), // workaround
    Key: key
  })
```

**Comment by vqvu** [comment] 2015-04-19 20:01
You'll either need to `pipe` to a through stream or use `wrap`, like you've found. Highland streams are not readable node stream.

PRs welcome for a `toNodeStream` transform that provides this functionality.

**Comment by wonderdogone** [comment] 2015-05-21 21:03
I might be able to help contribute to this. So to be clear as of now no method exists to turn a highland stream to a node stream?

**Comment by vqvu** [comment] 2015-05-22 00:20
Yes. That's correct. You can manually do it with `hlStream.pipe(through())` though.

**Comment by Neppord** [comment] 2015-07-17 14:34
I think this is a duplicate of #129.

**Closed** 2016-01-22 14:33 UTC
