### ISSUE TITLE
Pipeline not propagating Promise casted error properly

### ISSUE THREAD

**Issue by cphoover** [caolan/highland#391] opened 2015-11-17 04:13 UTC
it seems like when a stream is passed through a pipeline the error is not being propagated properly and the error handler is never called.

For instance while this works (as it should)

```js
'use strict';

var hi = require('highland'),
	Bluebird = require('bluebird');

function prependBlah(s) {
	return s.map(function (x) {
		return 'blah ' + x.toString();
	});
}

function appendAsdf(s) {
	return s.map(function (x) {
		return x.toString() + 'Asdf';
	});
}

function appendNewline(s) {
	return s.map(function (x) {
		return x.toString() + '\n';
	});
}

hi(function (push, next) {
	push(null, hi(Bluebird.resolve(1)));
	push(null, hi(Bluebird.resolve(2)));
	push(null, hi(Bluebird.reject(3)));
	setTimeout(next, 1000);
})
	.merge()
	.errors(function (err) {
		console.log('err', err);
	})
	.through(hi.pipeline.apply(null, [
		prependBlah,
		appendAsdf,
		appendNewline
	]))
	.pipe(process.stdout);
```

the below snippet of code causes the following error to be thrown: `Unhandled rejection Error: 3`

```js
'use strict';

var hi = require('highland'),
	Bluebird = require('bluebird');

function prependBlah(s) {
	return s.map(function (x) {
		return 'blah ' + x.toString();
	});
}

function appendAsdf(s) {
	return s.map(function (x) {
		return x.toString() + 'Asdf';
	});
}

function appendNewline(s) {
	return s.map(function (x) {
		return x.toString() + '\n';
	});
}

hi(function (push, next) {
	push(null, hi(Bluebird.resolve(1)));
	push(null, hi(Bluebird.resolve(2)));
	push(null, hi(Bluebird.reject(3)));
	setTimeout(next, 1000);
})
	.merge()
	.through(hi.pipeline.apply(null, [
		prependBlah,
		appendAsdf,
		appendNewline
	]))
	.errors(function (err) {
		console.log('err', err);
	})
	.pipe(process.stdout);
```

Seems like the error should be handled in both instances, and thus the promise chain should handle the rejection.  Maybe I am misunderstanding how pipeline and highland stream error handling is supposed to function.

**Comment by vqvu** [comment] 2015-11-17 05:41
The two examples you gave should behave the same way, so you're not misunderstanding.

But I can't reproduce the bug. What version of highland are you using? I'm using 2.5.1 and both of your examples print

```
blah 1Asdf
blah 2Asdf
err 3
```
every second.

**Comment by cphoover** [comment] 2015-11-17 15:55
I'm also using 2.5.1 strange....

**Comment by vqvu** [comment] 2015-11-18 04:42
Nevermind, I see it. I thought I correctly copied your second example, but apparently I didn't.

I ran it against master though, and it seems to work. My guess is it was fixed by #372. That PR was meant to fix `pipeline` behavior as it applies to node streams, but it did do a general rewrite of `pipeline`.

Can you verify that the code in master works for you?

Aside: Looks like 2.5.1 was released in May, which means it's probably time to do another release. I'll probably do this after #393 is merged.

**Comment by vqvu** [comment] 2015-11-18 05:15
Btw, using `pipeline` with `through` in this way is something of an anti-pattern. You can just as easily call `through` three times and pass it your handlers each time. `pipeline` is more meant to be used for interop with Node streams. You can even use `seq` if you don't want to type "through" all the time.

This is functionally equivalent to the version you had with `pipeline`.

```javascript
    .through(hi.seq(
        prependBlah,
        appendAsdf,
        appendNewline
    ))
```

**Comment by daywiss** [comment] 2016-09-19 00:26
im getting the same problem on the latest versions of highland and bluebird in npm.  can run here:

https://runkit.com/57df2d9f6dc2ad1400d34aa0/57df2db1db3774140022baad

When highland streamifies the promise, it signals unhandled rejection: 
```js
var Promise = require("bluebird");
var _ = require('highland')


function reject(){
    return Promise.reject('error')
}

function print(result){
    console.log(result)
}
//handled rejection
reject().then(print,print)

//unhandled rejection  
_(reject).errors(print).each(print)
```

**Comment by vqvu** [comment] 2016-09-19 02:23
Closing because the issue seems to be resolved in the latest version.

@daywiss, I got a notification of your comment, but since you've deleted it, I'll assume that you've worked out the issue that you had.

**Closed by vqvu** 2016-09-19 02:23 UTC
