### ISSUE TITLE
Feedback: Filebuffer through stream

### ISSUE THREAD

**Issue by kolpax** [caolan/highland#431] opened 2016-01-18 17:03 UTC
I implemented a filebuffer through stream that writes and reads to and from a file simultaneously. I am planning to use it in situations where we have to cache large incoming files to disk while they're being sent to the user over HTTP. As I in my case can't control the speed of the read stream, this implementation allows me buffer to disk instead of memory.

Any feedback would be much appreciated!

```es6
import fs from 'fs-promise'
import _ from 'highland'

export default function(filePath) {
  return s => {
    let eof = false

    const tmpFilePath = `${filePath}.tmp`
    const ws = fs.createWriteStream(tmpFilePath)

    const errors = _((push) => {
      s.pipe(ws)
        .on('finish', () => {
          eof = true
          push(null, _.nil)
          fs.rename(tmpFilePath, filePath)
            .catch((err) => fs.unlink(tmpFilePath))
        })
        .on('error', (err) => push(err))
    })

    const readStream = ({ start = 0 } = {}) => {
      return _(fs.createReadStream(eof ? filePath : tmpFilePath, { start }))
        .consume((err, x, push, next) => {
          if (err) {
            push(err, null)
          } else if (x === _.nil) {
            if (eof) {
              push(null, _.nil)
            } else {
              setTimeout(() => next(readStream({ start })), 1000)
            }
          } else {
            start += x.length
            push(null, x)
            next()
          }
        })
    }

    return _([errors, readStream()]).merge()
  }
}
```

**Comment by vqvu** [comment] 2016-01-19 08:58
At first glance, there seems to be a race condition where `eof` could be `true`, but the file hasn't been renamed, which can cause you to lose data (i.e., you try to read from `filePath` but it doesn't exist, causing an error to be pushed, then `nil`, which then causes you to stop since `eof == true`). 

You can set `eof` *after* the rename is complete. This is still a race condition, since the rename could be done but `eof == false`. In this case though, you'll just get a spurious error when trying to open `tmpFilePath` after it's been renamed (which you can suppress). I don't think there'll be data loss.

That said, if you're just using the file system as a temporary buffer, why do the rename at all?

The rest of your logic seems sound, though.

**Comment by ronag** [comment] 2016-01-23 22:05
Here is an updated version:

```javascript
import fs from 'fs-promise'
import _ from 'highland'
import cuid from 'cuid'

export default function(dstPath) {
  return s => {
    let eof = false

    const tmpPath = `${dstPath}.${cuid()}`
    const ws = fs.createWriteStream(tmpPath)

    const errors = _((push) => {
      s.pipe(ws)
        .on('finish', () => {
          fs.rename(tmpPath, dstPath)
            .catch(err => { /* Do nothing... */ })
            .then(() => {
              push(null, _.nil)
              eof = true
            })
        })
        .on('error', push)
    })

    const readStream = ({ srcPath, start = 0 } = {}) => {
      let position = start
      return _(fs.createReadStream(srcPath, { start: position }))
        .consume((err, x, push, next) => {
          if (err) {
            if (err.code === 'ENOENT' && srcPath === tmpPath) {
              next(readStream({
                srcPath: dstPath,
                start,
              }))
            }
            push(err, null)
          } else if (x === _.nil) {
            if (eof) {
              push(null, _.nil)
            } else {
              setTimeout(() => next(readStream({
                srcPath,
                start,
              })), 200)
            }
          } else {
            position += x.length
            push(null, x)
            next()
          }
        })
    }

    return _([errors, readStream({ srcPath: tmpPath })]).merge()
  }
}
```

**Comment by vqvu** [comment] 2016-01-27 02:33
You don't want to call `push` after redirecting to another stream using `next`. The `push(err, null)` should be gated behind an `else` clause. It also needs to call `next()` too.

Like this:

```javascript
          if (err) {
            if (err.code === 'ENOENT' && srcPath === tmpPath) {
              next(readStream({
                srcPath: dstPath,
                start: position,
              }))
            } else {
              push(err, null)
              next()
            }
          }
```

Otherwise, @ronag's solution seems reasonable.

**Comment by ronag** [comment] 2016-01-30 19:16
So given my current solution I'm getting corrupted data, @vqvu any ideas why?

```javascript
import fs from 'fs-promise'
import _ from 'highland'
import cuid from 'cuid'

export default function createFileBuffer(dstPath) {
  return s => {
    let eof = false

    const tmpPath = `${dstPath}.${cuid()}.tmp`
    const ws = fs.createWriteStream(tmpPath)

    const errors = _((push) => {
      s.pipe(ws)
        .on('error', push)
        .on('finish', () => {
          fs.rename(tmpPath, dstPath)
            .catch(err => ({
              // Do nothing...
            }))
          push(null, _.nil)
          eof = true
        })
    })

    const readStream = (srcPath, start) =>
      _(fs.createReadStream(srcPath, { start }))
        .consume((err, x, push, next) => {
          if (err) {
            if (err.code === 'ENOENT' && srcPath === tmpPath) {
              next(readStream(dstPath, start))
            } else {
              push(err, null)
              next()
            }
          } else if (x === _.nil) {
            if (eof) {
              push(null, _.nil)
            } else {
              setTimeout(() => next(readStream(srcPath, start)), 200)
            }
          } else {
            start += x.length
            push(null, x)
            return next()
          }
        })

    return _([errors, readStream(tmpPath, 0)]).merge()
  }
}
```
Reproducible by running an md5 on the input and the output and comparing...

**Comment by ronag** [comment] 2016-01-30 19:50
Ok, seems to work fine on the local file system however the following doesn't work:

```javascript
    s3.upload({
      Key: toKey(fileId),
      Body: s
         .through(filebuffer(dstPath))
        .pipe(new PassThrough({ objectMode: false }))
        .on('error', push),
      Bucket: config.aws.bucket,
    })
```
while this works:


```javascript
    s3.upload({
      Key: toKey(fileId),
      Body: s
        .pipe(new PassThrough({ objectMode: false }))
        .on('error', push),
      Bucket: config.aws.bucket,
    })
```

The corruption seems to occur in the beginning of the file...

**Comment by ronag** [comment] 2016-01-30 20:03
Ok. The problem here is that `filebuffer` starts 'hot'. Which means one has to call a `.pause` after converting it to a node stream using `s.pipe(new PassThrough())` i.e.

```javascript
    const Body = s
         .through(filebuffer(dstPath))
        .pipe(new PassThrough({ objectMode: false }))
        .on('error', push)
    Body.pause()
    s3.upload({
      Key: toKey(fileId),
      Body,
      Bucket: config.aws.bucket,
    })
```

@vqvu: Not quite sure what is going on here...

**Comment by vqvu** [comment] 2016-01-31 02:53
I'm not sure what's going on either. Needing to call `pause` doesn't make any sense, since node and highland streams both start paused. Plus, the only thing calling `pause` does is to keep the stream from an automatically calling `resume` when someone does `on('data')`. Problem is, it looks like the AWS SDK uses [`on('readable')`](https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L167) and [`read()`](https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L364). I don't see `on('data')` anywhere.

Unfortunately, I don't have an S3 bucket to play with. I've tried to reproduce this with the AWS logic but writing to the filesystem instead of over the network, and it seems to work fine ([gist](https://gist.github.com/vqvu/6e9d393e05824a77484f)).

What kind of corruption are you seeing? Are you missing chunks at the start of the file? Are some chunks out of order? Also, what version of node are you using?

**Comment by ronag** [comment] 2016-01-31 10:07
I'm missing data at the start of the file. Using nodejs 5.5.0.

**Comment by ronag** [comment] 2016-01-31 10:23
@vqvu: Could I somehow fool the aws code that a highland stream is  `instance of Stream` so that I don't have to convert it?

**Comment by vqvu** [comment] 2016-01-31 11:43
> Could it somehow be related to the PassThrough?

It's possible, though `PassThrough` is the [most trivial of all trivial implementations](https://github.com/nodejs/node/blob/v5.5.0/lib/_stream_passthrough.js), so if there is a problem, it's from the general `Transform` stream. The only thing I can think of is that `PassThrough`'s implementation of `_transform` is synchronous, and there may be a bug where sync code sometimes doesn't work. It's a far-fetched theory, but easy to check by just implementing a `PassThrough` that calls the callback asynchronously.

> Could also be related to that S3 will not read/write as fast as the local filesystem.

There's probably some race condition going on here, so this is likely related, but I have no idea in what way.

> a highland stream is instance of Stream so that I don't have to convert it?

I don't think so. Even if you could, you'd have to implement `read` and `on('readable')`, and that's way more work than just adding `pause`.

You need to figure out where the problem is coming from: Highland, AWS, or `PassThrough`. Since you're missing data, the first thing I would check is whether or not the AWS code is receiving all of the data from the stream in the right order. Looks like you can do that by adding some `console.log` to AWS's `fillStream` [here](https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L360) and manually checking that you see the correct data in the correct order.

If you see the right data in the right order, then it's likely an AWS bug. If you don't, then you should be able to reproduce this without AWS. The problem is at the start of the file, so it's unlikely that you'll need to simulate the slowness of the network to repro. The complex multi-part upload logic shouldn't have needed to execute yet.

Sorry I can't be of more help, but once you can reproduce without AWS (if AWS is not the problem), then I can do more.

**Comment by ronag** [comment] 2016-02-03 00:21
@vqvu Just had another case where I must call `pause` or I will get corrupted data in the beginning:

```javascript
      .pipe(new PassThrough())
      .pause()
      .on('end', () => {
        if (end) {
          res.end()
        }
      })
      .pipe(res, { end: false })
```

**Comment by vqvu** [comment] 2016-02-03 06:48
Hmm, that would suggest that that problem is either Highland or `PassThrough`. Does this case also use `filebuffer`?

**Comment by ronag** [comment] 2016-02-03 08:54
@vqvu: Yes it also uses file buffer

**Comment by jeromew** [comment] 2016-02-03 10:19
do you know what kind of corruption you have ? missing some bytes at the beginning ?

one remark : i would write

    eof = true
    push(null, _.nil)

instead of

    push(null, _.nil)
    eof = true

push will do a full cycle on the highland machinery and you probably want to "eof" information to be updated before that.

maybe log the positions when writing to see if there is intermingling here + @vqvu do you confirm it is ok to setTimeout(..next..) inside consume ?

+ it could be interesting to confirm than upon ENOENT, position = 0 in

    next(readStream({
      srcPath: dstPath,
      start: position,
     }))

there is probably a race condition that we don't see yet.

**Comment by ronag** [comment] 2016-02-03 15:59
Soo, we've done some updates that have solved some other issues but this one still remains:

```javascript
const tails = new Map()

export function createReadStream(srcPath, opts = {}) {
  if (typeof srcPath !== 'string') {
    throw new Error(`Invalid source path. Expected a string`)
  }

  srcPath = path.resolve(srcPath)

  const tail = tails.get(srcPath)

  if (!tail || tail.eof) {
    return _(fs.createReadStream(srcPath, opts))
  }

  return tail::createReadStreamImpl(srcPath, opts, tail)
}

function createReadStreamImpl(srcPath, opts = {}) {
  let position = opts.start || 0

  if (this.err) {
    return _((push) => {
      push(this.err)
      push(null, _.nil)
    })
  }

  return _(fs.createReadStream(this.path, opts))
    .consume((err, x, push, next) => {
      if (this.err) {
        push(this.err, null)
        push(null, _.nil)
      } else if (err) {
        if (err.code === 'ENOENT') {
          next(_(createReadStream(srcPath, {
            start: position,
            end: opts.end,
          })))
        } else {
          push(err, null)
          push(null, _.nil)
        }
      } else if (x === _.nil) {
        if (this.eof) {
          // TODO: Not sure about -1
          assert(!opts.end || position - 1 <= opts.end)
          push(null, _.nil)
        } else if (this.err) {
          // TODO: Review & Remove
          push(this.err, null)
          push(null, _.nil)
        } else {
          setTimeout(() => next(this::createReadStreamImpl(srcPath, {
            start: position,
            end: opts.end,
          })), 200)
        }
      } else {
        position += x.length
        // TODO: Not sure about -1
        assert(!opts.end || position - 1 <= opts.end)
        push(null, x)
        next()
      }
    })
}

export function write(stream, dstPath) {
  dstPath = path.resolve(dstPath)

  const tail = { path: `${dstPath}.${cuid()}.tmp` }

  // NOTE: File is created before stream outputs any data or not...
  const ws = fs.createWriteStream(tail.path)

  tails.set(dstPath, tail)

  return new Promise((resolve, reject) => {
    function onError(err) {
      if (tail.err) {
        return
      }

      tail.err = err
      tails.delete(dstPath)
      fs.unlink(tail.path)
        .catch(err => {
          logger.debug(err)
          /* Do nothing... */
        })
      reject(err)
    }

    stream
      .on('error', onError)
      .pipe(ws)
      .on('error', onError)
      .on('finish', () => {
        if (tail.err) {
          return
        }
        fs.rename(tail.path, dstPath)
          .catch(err => {
            logger.debug(err)
            /* Do nothing... */
          })
          .then(() => {
            tail.eof = true
            tails.delete(dstPath)
            resolve()
          })
      })
  })
}

export default function(dstPath) {
  return s => {
    write(s, dstPath)
      .catch(err => {
        // Do nothing...
      })
    return createReadStream(dstPath)
  }
}
```

I will try to create a minimal example over the weekend.

**Comment by vqvu** [comment] 2016-02-04 01:29
> do you confirm it is ok to setTimeout(..next..) inside consume ?

Yeah. That should be fine.

> it could be interesting to confirm than upon ENOENT, position = 0 in
> 
>     next(readStream({
>     srcPath: dstPath,
>     start: position,
>     }))

`position` can be anything here. `ENOENT` is only expected to get thrown after the temporary file is renamed, which can happen at any position. I believe the logic is:

1. Rename happens.
2. The currently consuming stream ends because the temporary file is no longer there.
3. `setTimeout(...next)` gets called.
4. `ENOENT` fires.
5. The stream switches to the non-temporary file.

**Comment by jeromew** [comment] 2016-02-04 08:47
I am surprised I would have thought that "rename" does not modify the file descriptor that is currently streaming and that ENOENT can only happen at the beginning. I did not try.

**Comment by vqvu** [comment] 2016-02-04 20:30
Hmm, what you're saying doesn't sound unreasonable. It could be that I'm wrong. I just ran the code as a whole. I haven't actually confirmed that `rename` acts like I described.

**Comment by ronag** [comment] 2016-02-05 08:22
rename and unlink doesn't affect open file descriptors on Linux.

**Comment by jeromew** [comment] 2016-02-05 09:33
@ronag. the last re-org of the code is a bit hard to read + as you sait unit tests on what is or is not working would be helpful.

Regarding the ENOENT, I understand this case only happens when the file has already been renamed when createReadStreamImpl starts. It can maybe happen for very small files. Do you confirm that this is your intent for this part of the code ?

In this case, I would add an assert because I think that position == (opts.start || 0)

I may be wrong as I am only thought-debugging this.

**Comment by ronag** [comment] 2016-02-05 10:26
`ENOENT` should/will only happen after the file has been renamed and you try to open it **again** with `fs.createReadStream`. Already open streams should/will not be affected by the rename.

**Comment by jeromew** [comment] 2016-02-05 10:31
I don't understand why you have

    if (err.code === 'ENOENT') {
          next(_(fs.createReadStream(srcPath, {
            start: position,
            end: opts.end,
          })))
     }

In my understanding, this can only happen at the beginning of a stream, hence, position should be equal to opt.start.

In fact this comment is trying to understand the fact that the beginning of your files was corrupted in some cases. using "position" here could explain missing bytes if position's value has changed for whatever reason.

**Comment by ronag** [comment] 2016-02-05 10:36
> In my understanding, this can only happen at the beginning of a stream, hence, position should be equal to opt.start.

No. It can happen any time when the writer finishes and renames the file to the final name. The reader then needs to be able to switch over to the final name from the tmp.

1. Write starts to 1.raw.tmp
2. Read starts from 1.raw which reads from 1.raw.tmp
3. Write finishes to 1.raw.tmp and file is renamed to 1.raw
4. Read has not yet finished, but 1.raw.tmp no longer exists, continue reading from 1.raw at the previous position.

**Comment by ronag** [comment] 2016-02-05 10:37
In my understanding, this can only happen at the beginning of a stream, hence, position should be equal to opt.start.
No. It can happen any time when the writer finishes and renames the file to the final name. The reader then needs to be able to switch over to the final name from the tmp.

Write starts to 1.raw.tmp
Read starts from 1.raw which reads from 1.raw.tmp
Write finishes to 1.raw.tmp and file is renamed to 1.raw
Read has not yet finished, but 1.raw.tmp no longer exists, continue reading from 1.raw at the previous position.

**Comment by jeromew** [comment] 2016-02-05 10:42
This was my question on rename vs file descriptors.
you say

    Read has not yet finished, but 1.raw.tmp no longer exists

but the file descriptor Read was streaming from has not disappeared so imho streaming should continue. Nevertheless, I have not tested this so I may be wrong and you seem to have tested this yourself.

**Comment by ronag** [comment] 2016-02-05 10:44
@jeromew: Updated code with comments.

**Comment by ronag** [comment] 2016-02-05 10:44
> but the file descriptor Read was streaming from has not disappeared so imho streaming should continue. Nevertheless, I have not tested this so I may be wrong and you seem to have tested this yourself.

You might be right. Let me think about it a bit and get back later. I'm just about to go into a meeting.

**Comment by ronag** [comment] 2016-02-05 10:48
@jeromew: It can happen if the write finishes while the timeout is running...

**Comment by jeromew** [comment] 2016-02-05 11:00
ok I haven't checked what happens when we are starving on the tmp file that is being written (does it really reach this branch ?). In any case, you are passing the opts here

    setTimeout(() => next(createReadStreamImpl(srcPath, {
              start: position,
              end: opts.end,
    })), 200)

and upon ENOENT, you really want this "opts.start" to be the beginning of the "follow-me" stream, not the potentially moving target that is "position". I am not saying that this is a bug, but position has many reasons to move while it seems to me that the start of the "follow-me" stream should be fixed when createReadStreamImpl is called.

**Comment by ronag** [comment] 2016-02-05 12:57
@jeromew: First of all thank you for the feedback!

Secondly I don't quite understand why you think it's suspicious and what do you think it should do instead?

Consider the following:

| Time | Reader | Writer|
|-----------------------------|
|   1 | position 5000 | - |
|   2 | eof | - |
|   3 | timeout | - |
|   4 | - | position: 5500 - |
|   5 | - | Rename file.raw.tmp => file.raw - |
|   6 | Open file.raw.tmp | - |
|   7 | ENOENT | - |
|   8 | Open file.raw @ position: 5000 | - |
|   9 | position: 5500 | - |
| 10 | EOF |  - |

**Comment by jeromew** [comment] 2016-02-05 13:26
suspicious in the sense that if for whatever reason

    } else {
          position += x.length
    ...
    }

is hit then you will have `Open file.raw.tmp @ position: wrong position`

I am not saying that it can happen (I am just "reading" code here) but the state machine is sufficiently complicated that I am just saying it could happen, especially if, as you said, you have a corrupted file in the end.

I am totally ok with the sequence you described. I would just like to be sure that Read asks for a read at pos 5000, it really happens at pos 5000.

the difference is just (your version)

    if (err.code === 'ENOENT') {
      next(_(fs.createReadStream(srcPath, {
      start: position,
      end: opts.end,
    })))
   }

compared with (my version)

    if (err.code === 'ENOENT') {
     next(_(fs.createReadStream(srcPath, {
       start: opts.start || 0,
       end: opts.end,
    })))
    }

Again, I may be wrong, but my version seems to do the same thing (since opts is defined in the setTimeout anyway) without the risk of position beeing updated by something.

Which is way I initially proposed an assert like

    assert(position == (opts.start || 0))

if this assert throws, I think this is a bug because position gets updated in an expected way + you would be missing chunks in the output (corruption)

**Comment by ronag** [comment] 2016-02-05 13:33
@jeromew: Now it finally makes sense. You are right. Thanks!

**Comment by ronag** [comment] 2016-02-05 13:38
@jeromew: You just gave me an idea how to simplify things by keeping an open fd.

```javascript
export function createReadStream(srcPath, opts = {}) {
  const tail = tails.get(srcPath)

  function createReadStreamImpl(srcPath, opts = {}) {
    let position = opts.start || 0

    const fileStream = fs.createReadStream(tail.path, { ...opts, autoClose: false })

    return _(fileStream)
      .consume((err, x, push, next) => {
        if (tail.err || err) {
          push(tail.err || err, null)
          push(null, _.nil)
        } else if (tail.eof) {
          if (tail.eof) {
            assert(!opts.end || position - 1 <= opts.end)
            fileStream.end()
            push(null, _.nil)
          }
        } else if (x === _.nil) {
          setTimeout(() => next(createReadStreamImpl(srcPath, {
            start: position,
            end: opts.end,
          })), 200)
        } else {
          position += x.length
          // TODO: Not sure about -1
          assert(!opts.end || position - 1 <= opts.end)
          push(null, x)
          next()
        }
      })
  }

  return _(fs.open(srcPath, 'r'))
    .flatMap(fd => createReadStreamImpl(srcPath, { ...opts, fd }))
}
```
Haven't tested for real yet.

**Comment by ronag** [comment] 2016-02-06 19:09
I think this solves the issue with `pause`.

I will open a new issue focusing specifically on it if turns up again.

Here is the final simplified code:

```javascript
export function createReadStream(srcPath, opts = {}) {
  srcPath = path.resolve(srcPath)

  const tail = tails.get(srcPath)

  if (!tail) {
    return _(fs.createReadStream(srcPath, opts))
  }

  const createReadStream = (fd) => _((push, next) => {
    const buffer = Buffer(8192)
    fs.read(fd, buffer, 0, buffer.length, null)
      .then((bytesRead) => {
        if (tail.err) {
          push(tail.err)
          push(null, _.nil)
        } else if (bytesRead > 0) {
          push(null, buffer.slice(0, bytesRead))
          next()
        } else if (tail.eof) {
          push(null, _.nil)
        } else {
          setTimeout(next, 200)
        }
      })
      .catch(err => {
        push(err)
        push(null, _.nil)
      })
  })

  return _(fs.open(tail.path, 'r'))
    .consume((err, x, push, next) => {
      if (err) {
        if (err.code === 'ENOENT') {
          next(_(fs.createReadStream(srcPath, opts)))
        } else {
          push(err)
        }
      } else if (x === _.nil) {
        push(null, _.nil)
      } else {
        next(createReadStream(x))
      }
    })
}
```

I think this solves kolpax's original question as well so we can probably close this issue?

**Comment by jeromew** [comment] 2016-02-06 19:30
Yep ok I'll close the issue now ; keep us posted

**Closed by jeromew** 2016-02-06 19:30 UTC
