### ISSUE TITLE
parallel and corrupted data?

### ISSUE THREAD

**Issue by ronag** [caolan/highland#328] opened 2015-06-29 16:38 UTC
I've noticed a strange occurrence. I'm reading raw compressed data from multiple files and then concatenating them:

```
   .map(url => _(request.get(url))
   .parallel(8)
   .through(decoder())
```
However, this results sometimes in corrupted data.

While the following works just fine:

```
   .map(url => _(request.get(url))
   .parallel(1)
   .through(decoder())
```

I don't have any reproducible example yet. The problem is somewhat intermittent.

**Comment by vqvu** [comment] 2015-06-29 17:17
Can you try testing against the latest master? `parallel` had a buffering bug where it would drop data in certain circumstances (see #234). This was fixed in #302 but has not yet been released.

**Comment by ronag** [comment] 2015-06-29 17:26
Will need to do some more testing but so far that seems to have solved it.

Looking forward to the next release :).

**Comment by ronag** [comment] 2015-06-29 17:28
Nope. Still a problem.

**Comment by vqvu** [comment] 2015-06-29 17:46
Do you know why the data is corrupted? Are the Buffers being dropped or reordered?

**Comment by ronag** [comment] 2015-06-29 17:47
It's very difficult to tell. It's H264 video buffers that are sent to ffplay. Analysing a H264 bitstream is a bit complicated.

**Comment by vqvu** [comment] 2015-06-29 19:40
Hmm, I tried reading a bunch of local files via `parallel` and couldn't find any issue.

I've pushed a debug branch here: https://github.com/vqvu/highland/tree/parallel-debug (vqvu/highland#parallel-debug).

Can you run this code against that branch? It should track the order of buffers that request emits and tell you if anything is wrong.

Don't forget to `npm update --dev` first!

```javascript
var counter = [];
var i = 0;
var checkState = {
    urlIndex: 0,
    bufIndex: 0
};

// Check correct version
_.whatAmI();
// => Highland 2.x. debug-parallel edition

stream.map(url => _(request.get(url)))
    .map(function (s) {
        var urlIndex = i++;
        counter[urlIndex] = 0;
        return s.map(function (buf) {
            return {
                index: [urlIndex, counter[urlIndex]++],
                buf: buf,
            };
        });
    })
    .parallel(8)
    .map(function (obj) {
        if (obj.index[0] === checkState.urlIndex + 1) {
            checkState.urlIndex++;
            checkState.bufIndex = 0;
        }

        if (obj.index[0] === checkState.urlIndex) {
            if (obj.index[1] !== checkState.bufIndex) {
                console.log('Corrupt data.', checkState, obj.index);
            }
            checkState.bufIndex++;
        }
        else {
            console.log('Corrupt data.', checkState, obj.index);
        }

        return obj.buf;
    })
   .through(decoder())
```

**Comment by ronag** [comment] 2015-06-29 20:46
How do I checkout a branch with npm?

**Comment by ronag** [comment] 2015-06-29 20:56
See also, https://github.com/caolan/highland/pull/330

**Comment by quarterto** [comment] 2015-06-29 21:22
@ronag you can run `npm install vqvu/highland#parallel-debug`

**Comment by quarterto** [comment] 2015-06-29 21:22
(depending on your shell, you might need to escape the `#`

**Comment by vqvu** [comment] 2015-06-30 01:03
Ok, I think I have a broken test case. Will type up the fix soon-ish. Though I'm not sure if this is the problem you're encountering or not.

```javascript
var s1 = _([1, 2, 3]);
var s2 = _([11, 12, 13]);
_([s1.fork(), s2, s1.fork()])
    .parallel(3)
    .consume(function (err, x, push, next) {
        push(err, x);
        if (x.buf === 21) {
            // Pause for a while.
            setTimeout(next, 1000);
        }
        else if (x !== _.nil) {
            next();
        }
    })
    .toArray(_.log);
// => [ 1, 2, 3, 11, 12, 13 ]
// should be
// => [ 1, 2, 3, 11, 12, 13, 1, 2, 3 ]
```

Basically, when `s1` ends, if

- `s2` has already ended, and
- the parallel stream is paused (caused by the decoder)

then anything that `s3` has already emitted gets dropped on the floow.

**Comment by vqvu** [comment] 2015-06-30 04:15
Can you try testing against the code in #331?

`vqvu/highland#parallel-issue-328`

**Comment by ronag** [comment] 2015-06-30 06:49
Will do later today.

**Comment by ronag** [comment] 2015-06-30 07:06
That seems to have solved it.

**Closed** 2015-06-30 15:43 UTC
Labels: bug

**Comment by vqvu** [comment] 2015-06-30 15:45
Please reopen if you run into the problem again.
