### ISSUE TITLE
Add .toPromise as analogy to .asCallback

### ISSUE THREAD

**Issue by Ginden** [caolan/highland#627] opened 2017-05-25 08:46 UTC
Very simple and useful addition:

```javascript
Stream.prototype.toPromise = function() {
    return new Promise((resolve, reject) => {
       this.toCallback((err, res) => err ? reject(err) : resolve(res));
    });
};
```

Pros:
* Enables direct integration with APIs designed to work with promises
* Enables direct integration with language constructs like `async/await`

Cons:
* Won't work in Node 0.10 and Internet Explorer without Promise polyfill.

**Comment by vqvu** [comment] 2017-05-25 09:14
You're not the first one to want this. See #289. I think the reasons articulated there for not having `toPromise` in the library still applies.

Note that it is fairly trivial to roll your own using `through`.

```javascript
function toPromise(stream) {
  return new Promise((resolve, reject) => {
    stream.toCallback((err, res) => err ? reject(err) : resolve(res));
  });
}

const thisIsAPromise = stream.through(toPromise);
```

**Comment by Ginden** [comment] 2017-05-25 12:54
> I think the reasons articulated there for not having toPromise in the library still applies.

I'm sure there is no user who would want to use `.toPromise` method without depending on promises - especially when it's a part of language.

BTW compatibility with environments isn't stated in documentation anyway (and Highland requires ES5 anyway).

**Comment by vqvu** [comment] 2017-05-25 20:56
> I'm sure there is no user who would want to use `.toPromise` method without depending on promises

It's about an having an implicit dependency within certain parts of the API on some global symbol that may or may not exist. It's part of the language, but (as you mention) not every relevant JS engine implements it.

Compatibility isn't explicitly stated, but we test against 0.10+ (so people can reasonably assume that we support it). And there is an effort made to support ES3 (though we don't test this, so I concede that this may not be the case). Regardless, ES5 doesn't define Promises, so I don't understand the point of your parenthetical.

That said, I would be fine with an implementation that does not have the implicit dependency. Essentially

```javascript
Stream.prototype.toPromise = function(PromiseContructor) {
    return new PromiseContructor((resolve, reject) => {
       this.toCallback((err, res) => err ? reject(err) : resolve(res));
    });
};
```

PR welcome.

**Comment by angelf** [comment] 2017-06-03 17:50
Why is not acceptable to sniff for global.Promise and if it's not there throw an exception?. Any user that calls .toPromise will be well aware that this requires a Promises implementation.

**Comment by vqvu** [comment] 2017-06-03 22:36
I don't like adding an implicit dependency on something that is not always there, as that means correct usage of `toPromise` depends on the environment and not just on the local code. It's too easy for something to go wrong.

It would be different if Promises were core to the functionality of the library, since it would be clear that the library can't work at all without a Promise implementation. Requiring the user to pass in a Promise implementation all the time in such a library would significantly affect its usability. But what we have here is a fairly trivial, nice-to-have helper for interop with a Promises, so I am ok with taking a slight hit in usability in exchange for the removal of the implicit dependency.

**Comment by vqvu** [comment] 2017-06-06 21:25
I don't think it's so odd. Highland consumes a lot of things that it doesn't let you get back out (like arrays or Iterables). In fact, streams are strictly more powerful than promises (since they can handle multiple asynchronous values instead of just one), so I would expect it to be easier to convert from Promises to streams than the other way around.

Plus, I'm not saying we shouldn't have an easy way to convert back to a promise (`toCallback` was partly written to facilitate this). I'm just saying that since Promises aren't completely universal yet, users need to take the (imo minor) step of providing a Promise constructor when they convert.

**Comment by corbinu** [comment] 2017-06-14 17:37
Just came across this project for an issue I was having, but I am very confused by this discussion @vqvu How are Promises not universal yet? There is no version of node that has been in security updates in over 6 months that does not support them.
https://github.com/nodejs/LTS

**Comment by svozza** [comment] 2017-06-14 17:59
But there are tonnes of browsers that don't have them.

**Comment by corbinu** [comment] 2017-06-14 18:33
@svozza Thats what https://github.com/stefanpenner/es6-promise is for. I have a whole bunch of webapps thats support all the way back to IE8 but have dependencies that depend on promises. 
https://github.com/mzabriskie/axios for exmaple

**Comment by vqvu** [comment] 2017-06-15 08:09
I understand that polyfills exist. They are not the problem. The problem isn't even an implicit dependency on a global `Promise`&mdash;not by itself anyway. As I've [said before](https://github.com/caolan/highland/issues/627#issuecomment-306005508), there's nothing wrong with depending on `Promise` if it is core to the functionality of the library. Axios is a perfect example of such a library. Highland is not.

It comes down to a trade-off between developer user experience and implicit dependency on global state. For example, axios can choose to make all of its API require the user pass in a promise constructor, but that would be extremely annoying for their users. In their case, the improved user experience outweighs any issues that depending on `Promise` can cause.

For Highland, I think it's the opposite. `toPromise` is only useful when you need to interop with libraries or language features that require promises. It's use should be rare in comparison to other parts of the Highland API. The slight improvement in user experience from not requiring the promise constructor is not worth it. It's a value judgement. You may disagree.

Note that #628 was merged, so I'm not completely opposed to the idea of a `toPromise` method.

**Comment by corbinu** [comment] 2017-06-15 17:46
That exactly my point though. You can easily make just toPromise be the only part of the library fail if promises are not available. So your hurting developer user experience for all Node developers and for a very large segment of browser developers who either A) don't target old IE or B) Already pollyfill for some other dependency. 

Adding the feature does not affect the experience developers who done use promises in the slightest. Not adding it directly affects developers who do use Promises/Async/Await.

**Comment by vqvu** [comment] 2017-06-16 08:09
I don't know what else I can say except, I disagree. I just don't think it hurts usability all that much. We're talking about

```javascript
stream.toPromise(Promise)
```

instead of

```javascript
stream.toPromise()
```
here. And having an API that works the same everywhere is not worth nothing. There is *some* line beyond which the latter trumps the former, and I think that's where we are.

**Comment by corbinu** [comment] 2017-06-16 17:28
Ok no worries ... that's the good news about software is we can always disagree. Like I said in my post. I was simply confused on why this was an issue (That mostly revolved around the issue of why Node 0.10 and IE8 support without a pollyfill should matter for anything not promise specific).

Honestly at this point I just took a couple days and implemented what I needed myself. Best of luck.

**Comment by darky** [comment] 2017-06-18 22:33
https://github.com/caolan/highland/pull/630 Here ability to use `.toPromise()` without passing `Promise` (it default)

**Comment by vqvu** [comment] 2017-06-18 23:48
Released as 2.11.0/3.0.0-beta.5

**Closed by vqvu** 2017-06-18 23:48 UTC

**Comment by darky** [comment] 2017-06-19 10:05
`stream.toPromise(Promise)` is API design, that smell bad. Library should by default use `Promise` constructor and don't require to pass `Promise` noise in 90% cases. For "old fags", who don't have native Promise support need to add ability to setup own Promise constructor. It can be passed directly in `.toPromise` as now or/and global setup like https://marionettejs.com/docs/v2.4.4/marionette.configuration.html#overriding-marionettedeferred

**Comment by vqvu** [comment] 2017-06-19 10:40
I am not particularly interested in continuing to beat a dead horse. I've already explained my rationale behind the `toPromise(Promise)` signature. If you disagree, you are free to implement your own transform via one of the following methods

1. As a [through-transform](https://github.com/caolan/highland/issues/627#issuecomment-303962728)
2. By directly patching the Highland prototype (not recommended, and we won't support any issues that arise).
3. With the [new `use` feature](https://github.com/caolan/highland/blob/master/lib/index.js#L949) in the 3.0.0 beta (`npm install highland@next`).
    ```javascript
    const Highland = require('highland');
    const _ = Highland.use({
      toPromise() {
        return Highland.toPromise(Promise, this);
      }
    });

    _([1]).toPromise()
      .then(x => console.log(x));  // => 1
    ```
    Sorry that documentation for it doesn't exist yet.

**Comment by rightaway** [comment] 2017-06-28 10:12
Could anyone provide a practical example on when `toPromise` could be used? I'm using highland and am curious if I could simplify my existing code by using this.

**Comment by vqvu** [comment] 2017-06-30 22:35
I would say any of the uses of promises that you bring up in #593 could be improved slightly with `toPromise`.

Usages of
```javascript
new Promise((resolve, reject) => {
  stream.someTransform(...)
      ...
      .stopOnError(reject)
      .done(resolve);
```

could be replaced with
```javascript
stream.someTransform(...)
    ...
    .stopOnError((e, push) => push(e))
    .filter(x => false)
    .toPromise(Promise);
```

or, if you convert to promises often, with
```javascript
// Defined once.
function toCompletedPromise(stream) {
  return stream.stopOnError((e, push) => push(e))
      .filter(x => false)
      .toPromise(Promise);
}

stream.someTransform(...)
    ...
    .transform(toCompletedPromise);
```
