### ISSUE TITLE
Website "Download" button points to source with local file paths

### ISSUE THREAD

**Issue by chanced** [caolan/highland#339] opened 2015-07-09 20:10 UTC
I was just looking through the source via the [direct download link](https://cdn.rawgit.com/caolan/highland/2.5.1/dist/highland.js ) on highlandjs.org and noticed that it had local file paths from the build. 

The paths point to ```/home/jwagner/gh-highland/node_modules/browserify/node_modules/insert-module-globals/node_modules/process/browser.js``` and so on.

There are at least 4 occurrences on line numbers: 4124 ,4125, 6620, 6621

```javascript
}).call(this,_dereq_("/home/jwagner/gh-highland/node_modules/browserify/node_modules/insert-module-globals/node_modules/process/browser.js"),typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
},{"./support/isBuffer":9,"/home/jwagner/gh-highland/node_modules/browserify/node_modules/insert-module-globals/node_modules/process/browser.js":7,"inherits":6}]},{},[1])
(1)
});
```

**Comment by quarterto** [comment] 2015-07-09 20:29
Dupe of #338

**Closed by quarterto** 2015-07-09 20:29 UTC
